# This is a basic workflow to help you get started with Actions

name: Deploy Blazor WASM to Github Pages

on:
  push:
    branches:
      - master  # Change this to the branch you want to deploy from

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Add .nojekyll file
      run: touch .nojekyll
      
    - name: Change base-tag in index.html from / to BlazorGitHubPagesDemo
      run: sed -i 's/<base href="\/" \/>/<base href="\/World-Builder\/" \/>/g' index.html
      
    - name: copy index.html to 404.html
      run: cp index.html 404.html
      
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./
